import marshal

py313_opnames = {
    0: 'CACHE',
    1: 'POP_TOP',
    2: 'ROT_TWO',
    3: 'ROT_THREE',
    4: 'DUP_TOP',
    5: 'DUP_TOP_TWO',
    6: 'NOP',
    7: 'UNARY_POSITIVE',
    8: 'UNARY_NEGATIVE',
    9: 'UNARY_NOT',
    10: 'UNARY_INVERT',
    11: 'BINARY_MATRIX_MULTIPLY',
    12: 'BINARY_POWER',
    13: 'BINARY_MULTIPLY',
    14: 'BINARY_MODULO',
    15: 'BINARY_ADD',
    16: 'BINARY_SUBTRACT',
    17: 'BINARY_SUBSCR',
    18: 'BINARY_FLOOR_DIVIDE',
    19: 'BINARY_TRUE_DIVIDE',
    20: 'INPLACE_FLOOR_DIVIDE',
    21: 'INPLACE_TRUE_DIVIDE',
    22: 'STORE_SUBSCR',
    23: 'DELETE_SUBSCR',
    24: 'BINARY_LSHIFT',
    25: 'BINARY_RSHIFT',
    26: 'BINARY_AND',
    27: 'BINARY_XOR',
    28: 'BINARY_OR',
    29: 'INPLACE_ADD',
    30: 'INPLACE_SUBTRACT',
    31: 'INPLACE_MULTIPLY',
    32: 'INPLACE_MATRIX_MULTIPLY',
    33: 'INPLACE_POWER',
    34: 'INPLACE_MODULO',
    35: 'INPLACE_LSHIFT',
    36: 'INPLACE_RSHIFT',
    37: 'INPLACE_AND',
    38: 'INPLACE_XOR',
    39: 'INPLACE_OR',
    40: 'GET_AITER',
    41: 'GET_ANEXT',
    42: 'BEFORE_ASYNC_WITH',
    43: 'END_ASYNC_FOR',
    44: 'INPLACE_OP',
    45: 'IS_OP',
    46: 'CONTAINS_OP',
    47: 'JUMP_IF_NOT_EXC_MATCH',
    48: 'JUMP_BACKWARD',
    49: 'JUMP_FORWARD',
    50: 'POP_JUMP_FORWARD_IF_TRUE',
    51: 'POP_JUMP_FORWARD_IF_FALSE',
    52: 'CALL',
    53: 'CALL_INTRINSIC_1',
    54: 'CALL_INTRINSIC_2',
    55: 'CALL_INTRINSIC_3',
    56: 'CALL_KW',
    57: 'CALL_METHOD',
    58: 'CALL_FINALLY',
    59: 'POP_EXCEPT',
    60: 'POP_FINALLY',
    61: 'LOAD_GLOBAL',
    62: 'DELETE_DEREF',
    63: 'RAISE_VARARGS',
    64: 'RERAISE',
    65: 'RETURN_VALUE',
    66: 'RETURN_GENERATOR',
    67: 'RETURN_LAST',
    68: 'BREAK_LOOP',
    69: 'CONTINUE_LOOP',
    70: 'WITH_CLEANUP_START',
    71: 'WITH_CLEANUP_FINISH',
    72: 'LOAD_CONST',
    73: 'LOAD_NAME',
    74: 'BUILD_TUPLE',
    75: 'BUILD_LIST',
    76: 'BUILD_SET',
    77: 'BUILD_MAP',
    78: 'BUILD_TUPLE_UNPACK_WITH_CALL',
    79: 'BUILD_LIST_UNPACK',
    80: 'BUILD_SET_UNPACK',
    81: 'BUILD_MAP_UNPACK',
    82: 'BUILD_MAP_UNPACK_WITH_CALL',
    83: 'LOAD_DEREF',
    84: 'LOAD_FAST',
    85: 'LOAD_FAST_AND_CLEAR',
    86: 'STORE_FAST',
    87: 'DELETE_FAST',
    88: 'LOAD_GLOBAL_AND_NULL',
    89: 'LOAD_METHOD',
    90: 'LOAD_ATTR',
    91: 'LOAD_FROM_DICT_OR_GLOBALS',
    92: 'LOAD_FROM_DICT_OR_GLOBALS_WITH_CACHE',
    93: 'LOAD_ATTR_WITH_CACHE',
    94: 'MAKE_CELL',
    95: 'GET_LEN',
    96: 'MATCH_MAPPING',
    97: 'MATCH_SEQUENCE',
    98: 'MATCH_KEYS',
    99: 'COPY',
    100: 'COPY_REGISTERED',
    101: 'PUSH_NULL',
    102: 'POP_REGISTERED',
    103: 'POP_JUMP_BACKWARD_IF_TRUE',
    104: 'POP_JUMP_BACKWARD_IF_FALSE',
    105: 'GET_YIELD_FROM_ITER',
    106: 'GET_AWAITABLE',
    107: 'BEFORE_WITH',
    108: 'SET_FUNCTION_ATTRIBUTE',
    109: 'STORE_DEREF',
    110: 'STORE_ATTR',
    111: 'STORE_GLOBAL',
    112: 'DELETE_GLOBAL',
    113: 'DELETE_ATTR',
    114: 'NEGATE_EXCEPTION',
    115: 'CHECK_EXC_MATCH',
    116: 'CHECK_EG_MATCH',
    117: 'CHECK_EXC',
    118: 'CHECK_EG',
    119: 'LIST_TO_TUPLE',
    120: 'RETURN_GENERATOR_AND_CLEANUP',
    121: 'CONVERT',
    122: 'MAKE_FUNCTION',
    123: 'MAKE_CLOSURE',
    124: 'KW_NAMES',
    125: 'COPY_FREE_VARS',
    126: 'SET_UPDATE',
    127: 'MAP_UPDATE',
    128: 'LOAD_CLOSURE',
    129: 'LOAD_CLOSURE_AND_CLEAR',
    130: 'PUSH_EXC_INFO',
    131: 'FORMAT_VALUE',
    132: 'BUILD_CONST_KEY_MAP',
    133: 'BUILD_STRING',
    134: 'LOAD_STR',
    135: 'MATCH_CLASS',
    136: 'JUMP_IF_NOT_DEBUG',
    137: 'LOAD_ASSERTION_ERROR',
    138: 'RESUME',
    139: 'CO_FUTURE_FLAGS',
    140: 'SETUP_FINALLY',
    141: 'END_FINALLY',
    142: 'SETUP_EXCEPT',
    143: 'SETUP_ASYNC_WITH',
    144: 'SETUP_ANNOTATIONS',
    145: 'YIELD_VALUE',
    146: 'YIELD_FROM',
    147: 'SEND',
    148: 'POP_JUMP_FORWARD_IF_NOT_NONE',
    149: 'POP_JUMP_BACKWARD_IF_NOT_NONE',
    150: 'POP_JUMP_FORWARD_IF_NONE',
    151: 'POP_JUMP_BACKWARD_IF_NONE',
    152: 'JUMP_IF_NOT_NONE_OR_POP',
    153: 'JUMP_IF_NONE_OR_POP',
    154: 'POP_JUMP_FORWARD_IF_NOT_EXC_MATCH',
    155: 'POP_JUMP_BACKWARD_IF_NOT_EXC_MATCH',
}

with open('/Users/admin/codes/Tools/PyRebuilderSharp/test_data/compiled/reprlib.3.13.pyc', 'rb') as f:
    f.read(16)
    code_obj = marshal.load(f)

for c in code_obj.co_consts:
    if hasattr(c, 'co_name') and c.co_name == 'recursive_repr':
        for d in c.co_consts:
            if hasattr(d, 'co_name') and d.co_name == 'decorating_function':
                print(f"=== decorating_function (Python 3.13 opcodes) ===")
                print(f"co_varnames: {d.co_varnames}")
                print(f"co_cellvars: {d.co_cellvars}")
                print(f"co_freevars: {d.co_freevars}")
                print(f"co_names: {d.co_names}")
                print(f"\nLocalsplus layout:")
                print(f"  [0] user_function (varnames[0])")
                print(f"  [1] wrapper (varnames[1])")
                print(f"  [2] user_function (cellvars[0])")
                print(f"  [3] repr_running (cellvars[1])")
                print(f"  [4] fillvalue (freevars[0])")
                print()
                
                code = bytes(d.co_code)
                print("Bytecode disassembly (Python 3.13):")
                for i in range(0, len(code), 2):
                    op = code[i]
                    arg = code[i+1]
                    opname = py313_opnames.get(op, f'UNKNOWN_{op}')
                    print(f'0x{i:04X}: op={op:3d} ({opname}) arg={arg:3d}')
                break
        break
